### ISSUE TITLE
RFC: Separate Lists for Anime and Manga

### ISSUE THREAD

**Issue by ccubed** [ccubed/PyMoe#10]
In an effort to bring improvements where I can, I envision that, based on #8, one of the most common things that would be done with Anime and Manga lists would be separating them by status. I'd like to make PyMoe more friendly by doing that on the backend, but I'd like to know if this would break a use case for anyone. 

To explain, what I envision is that when you use any method that returns a list of Anime or Manga objects (including user), you would get a structure like this:
```py
a = instance.anime.search("Bleach")
a.airing # list of all currently airing anime
a.dropped # list of all dropped anime
```

And so on, same with manga. I am asking for comments and opinions on this change before making it because it's fairly breaking, but I think it's worth the break.

**Comment by ccubed** [comment]
Assuming I get no responses on this, I'm going to go ahead and implement this end of week.

**Comment by lethargilistic** [comment]
I actually had the same idea for my fork. If you're interested in one way to do this, you can [check it out.](https://github.com/lethargilistic/PyMoe/blob/filters/Pymoe/Mal/Abstractions.py#L19) I'm going to investigate ways to save space, but it's pretty fast as it is and it works for both Anime and Manga. Cheers.

**Comment by ccubed** [comment]
This is done and has been tested, but I haven't added it to pypi.
