### ISSUE TITLE
Kitsu

### ISSUE THREAD

**Issue by ccubed** [ccubed/PyMoe#13]
Add Kitsu's edge api. I'm not going to bother with that yearly endpoint.

**Comment by ghost** [comment]
Any ETA? I'm quite interested in this.

**Comment by ccubed** [comment]
I'm beginning to work on this as of today. I was working on Earl.

**Comment by ccubed** [comment]
As of 547a8476d589efa950795a2e51d554dbfdf9cb4e this exists.
