### ISSUE TITLE
[Request] Better Docs

### ISSUE THREAD

**Issue by ghost** [ccubed/PyMoe#14]
There's no documentation on how to install the lib.

**Comment by ccubed** [comment]
There are two options.

If you want stable: pip
```
pip install PyMoe
```
see https://pypi.python.org/pypi/PyMoe/0.7.2

If you want bleeding age that might break: source
```
git clone my repo
python setup.py install
```
Occasionally git pull to check for new versions and run setup.py install again.

**Comment by ghost** [comment]
Should be in the docs you provide here : https://pymoe.readthedocs.io/en/latest/?badge=latest
