### ISSUE TITLE
Add Kitsu mappings support

### ISSUE THREAD

**Issue by liilac** [ccubed/PyMoe#21]
See https://github.com/ccubed/PyMoe/pull/20 for a very basic start.

Kitsu mappings support would allow users to identify Kitsu entries using external site IDs.

This is very useful where you are using another program, such as Sonarr, that uses databases with comparatively poor anime support for its metadata.

**Comment by ccubed** [comment]
Put in as of 6b33d4a1455d04b520dd76cbe157a686e47e9fb1.
Changed up as of 8263651c8a178cde5dad36dc30663b09a550eb56.
All working good.
