### ISSUE TITLE
Error from using Mal

### ISSUE THREAD

**Issue by CharmingDays** [ccubed/PyMoe#22]
`from Pymoe import Mal;
se=Mal(username="username", password="password");
sd=se.user('PaladinAlchemist').anime.list.completed;`

I get this whenever I try to execute the code above.

UnicodeEncodeError: 'ascii' codec can't encode characters in position 33686-33693: ordinal not in range(128)

Traceback (most recent call last):
  File "d:/Python/test.py", line 8, in <module>
    sd=se.user('PaladinAlchemist').anime.list.completed
  File "D:\Python2\lib\site-packages\Pymoe\Mal\__init__.py", line 294, in user
    root = ET.fromstring(anime_data.text)
  File "D:\Python2\lib\xml\etree\ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "D:\Python2\lib\xml\etree\ElementTree.py", line 1657, in feed
    self._parser.Parse(data, 0)

**Comment by ccubed** [comment]
This is an issue with your terminal not being able to display the character correctly. I don't have this problem in 3.6 on windows 10 using cmd or cmder so the terminal fixes in 3.6 have fixed this. 3.5.4 appears to have issues with `Kaze no Tani no Nausicaä`. I fixed this in 3.5.4 using the tried and true method of `chcp 65001`.

I suggest moving to 3.6 or reading more about this issue and ways to solve it here: 
https://stackoverflow.com/questions/6344853/python-unicode-in-windows-terminal-encoding-used

**Comment by CharmingDays** [comment]
Thanks!
