### ISSUE TITLE
AniList romaji issue

### ISSUE THREAD

**Issue by aizoule** [ccubed/PyMoe#25]
`animename = search['data']['Page']['media'][0]['title']['romaji']`
`animename_en = animename = search['data']['Page']['media'][0]['title']['english']`
`embed = discord.Embed(title=animename + " (English: " + animename_en + ")", color=0x2a9ff, url="https://anilist.co/anime/{}".format(ide))`
I am using these codes for my discord bot and the result is this:
![resim](https://user-images.githubusercontent.com/39998451/43995950-946ebabc-9dc1-11e8-8206-c4bab12bc869.png)
Should'nt this title would be like
> Shingeki no Kyojin (English: Attack on Titan) 

As you can see in the [AniList page](https://anilist.co/anime/16498/Shingeki-no-Kyojin/) *Romaji* shows the name as *Shingeki no Kyojin*.

**Comment by ccubed** [comment]
Verified this was working on the latest pip release 1.0.6.

```python
>>> a = instance.search.anime("Attack on Titan")
>>> a
{'data': {'Page': {'pageInfo': {'total': 12, 'currentPage': 1, 'lastPage': 4, 'hasNextPage': True}, 'media': [{'id': 16498, 'title': {'romaji': 'Shingeki no Kyojin', 'english': 'Attack on Titan'}, 'coverImage': {'large': 'https://cdn.anilist.co/img/dir/anime/reg/16498.jpg'}, 'averageScore': 81, 'popularity': 59344, 'episodes': 25, 'season': 'SPRING', 'hashtag': None, 'isAdult': False}, {'id': 99634, 'title': {'romaji': 'Shingeki no Kyojin: Lost Girls', 'english': 'Attack on Titan: Lost Girls'}, 'coverImage': {'large': 'https://cdn.anilist.co/img/dir/anime/reg/99634-W1WHgCw8wgmN.jpg'}, 'averageScore': 75, 'popularity': 5243, 'episodes': 3, 'season': 'FALL', 'hashtag': '#shingeki', 'isAdult': False}, {'id': 99147, 'title': {'romaji': 'Shingeki no Kyojin 3', 'english': 'Attack on Titan Season 3'}, 'coverImage': {'large': 'https://cdn.anilist.co/img/dir/anime/reg/99147-tbXmbeLCtfAw.jpg'}, 'averageScore': 81, 'popularity': 20104, 'episodes': 24, 'season': 'SUMMER', 'hashtag': '#shingeki', 'isAdult': False}]}}}
>>> a['data']['Page']['media'][0]['title']['romaji']
'Shingeki no Kyojin'
>>> a['data']['Page']['media'][0]['title']['english']
'Attack on Titan'
```

Having verified it isn't my library having a stroke, I can tell you with confidence the issue is this:
```python
animename_en = animename =search['data']['Page']['media'][0]['title']['english']
```

On this line you set animename_en equal to animename which then you set equal to the english name. So when you print them, they're both going to return Attack on Titan. You probably didn't mean to have animename in the middle there.
