### ISSUE TITLE
Kitsu Get Item from Library Entry

### ISSUE THREAD

**Issue by XVicarious** [ccubed/PyMoe#27]
Right now the library entries are in the "LibraryEntries" format.

Example library entry url: `https://kitsu.io/api/edge/library-entries/26975068`

#26 allows the filtering of the library entries by type, so the "/anime", "/manga", etc links work to get the item.

However, "/media" leads directly to the media in question without knowing the kind.

Is this something that you would want to implement? If so, I could make another pull request. Also if so, how would you want it to be formatted?

**Comment by ccubed** [comment]
I'll talk about both. 

I don't want to do anything with '/media' because there can be more than one result on the page. If there was only ever going to be one result on the page (see external mappings) then it makes sense to just go directly to '/media.'

In terms of #26 , I don't want to just slap params into the required arguments for the function. If we want to filter by kind, I think that's okay and could be exposed by a single argument that defaults to 'anime,manga'. Anything else I'd rather the user put in on their own.

If you wanted to redo a pull request to just have that one argument with a default i'd accept.

**Comment by XVicarious** [comment]
Not even a helper function to get the media item from the entry? Like `get_from_library_entry` or something? Without that it kind of makes the library functionality of the library useless. You just might as well just write the couple of lines to get the library and the item yourself.

As for the filters for the library fetching, the issue lies in that filtering the media kind is not the only filter that you can use. There is also status, dates, etc. But I could add named parameters for each of the filters I suppose.

**Comment by ccubed** [comment]
I hadn't thought of that. You're correct that just having kind will mess with the ability to add other filter parameters. In that case, the params argument is the best solution but it should default to None. 

Before I answer about the media call, can you explain to me what you want to do with media given a user's library entries?

**Comment by XVicarious** [comment]
When a user iterates through library entries, have a function available that will fetch the media info for that entry. I should note that it would still be up to the user to call this function.

Personally I'd recommend a `get_media(entryId)` function. Basically it will just fetch and return the results of `https://kitsu.io/api/edge/library-entries/{entry-id}/media`. It's not a huge thing, but it just makes it more user-friendly.

Personally I'm not a huge fan of the structure of the Kitsu API, and a function like that just makes it more bearable to use.

I guess for me the point of an API wrapper like this is to return results for the calls in a useful way. Leaving it as a raw library entry with no built in way to return the arguably most important information is a mistake imo. 

Plus, the project tagline:  
>the only python lib you'll ever need if you need the animu/mangu on the python platform

**Comment by ccubed** [comment]
Oh, yeah. That sounds good. I'm glad I asked because that is not what I was thinking.

**Comment by ccubed** [comment]
I merged #26.

**Comment by ccubed** [comment]
I merged #28. So if you want to submit for get I'll merge that too.
