### ISSUE TITLE
Unify API

### ISSUE THREAD

**Issue by tomerghelber** [ccubed/PyMoe#29]
Hello,

I played a little with the API, and I must thank you for the hard work.
Something that bugs me is the different code I had to write to wrap this package.
Is there a way to merge them and make them look the same (more object oriented)?
Maybe create an abstract client with specifications for each client?

Thanks.

**Comment by ccubed** [comment]
Fixed as of 18e6c0be51402a3e51d7a31258a7c7fee4e498b6.

Now just polishing the interfaces.

**Comment by ccubed** [comment]
I realize this is a full year later, however you can now download Version 2 with the unified API off of pypi using `python -m pip install pymoe`.
