### ISSUE TITLE
Doesn't return 'popularity' and 'idMal' from Anilist

### ISSUE THREAD

**Issue by K0-RR** [ccubed/PyMoe#39]
What I'm getting using official API:
`{'data': {'Media': {'id': 138788, 'meanScore': 63, 'averageScore': 62, 'popularity': 14205, 'idMal': 49766, 'title': {'romaji': 'Under Ninja', 'english': 'UNDER NINJA', 'native': 'アンダーニンジャ'}}}}`

What I'm getting using pymoe.anime.get.anilist.show(138788):
<details><summary>Output</summary>

`{'data': {'Media': {'title': {'romaji': 'Under Ninja', 'english': 'UNDER NINJA', 'native': 'アンダーニンジャ'}, 'startDate': {'year': 2023, 'month': 10, 'day': 6}, 'endDate': {'year': 2023, 'month': 12, 'day': 22}, 'coverImage': {'extraLarge': 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx138788-CXUvAraN1xha.jpg', 'large': 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx138788-CXUvAraN1xha.jpg', 'medium': 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx138788-CXUvAraN1xha.jpg', 'color': None}, 'bannerImage': 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/138788-EegwXUtH8iJR.jpg', 'format': 'TV', 'status': 'RELEASING', 'episodes': 12, 'season': 'FALL', 'seasonYear': 2023, 'description': 'Ninjas still exist in Japan today. They number around 200,000. The ninja organization NIN (National Intelligence of NINJA) is not controlled by the civilian government, with its elite members performing assassinations and sabotage in secret. There is an organization that opposes NIN: UN (Under Ninja). Ninja versus ninja: What lies waiting at the end of this shadowy feud?<br>\n<br>\n(Source: Crunchyroll)', 'averageScore': 62, 'meanScore': 63, 'genres': ['Action', 'Comedy'], 'synonyms': [], 'isAdult': False, 'siteUrl': 'https://anilist.co/anime/138788', 'nextAiringEpisode': {'timeUntilAiring': 424363, 'airingAt': 1703176080}, 'streamingEpisodes': [{'title': 'Episode 11 - Kuro Finally Took Up a Sword', 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire3-tmb/8c82b19d02fbfd73cfe12ce166eec4ff1702577688_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-11-kuro-finally-took-up-a-sword-911507', 'site': 'Crunchyroll'}, {'title': 'Episode 10 - DAYS GONE BY AND DAYS TO COME', 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire1-tmb/e902cd08a646f5d257599b358f7704f01701970559_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-10-days-gone-by-and-days-to-come-911506', 'site': 'Crunchyroll'}, {'title': "Episode 9 - I'm Gonna Go Down in Shinobi History", 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire4-tmb/549313c03b514b7d0c55b54dac671d291701363569_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-9-im-gonna-go-down-in-shinobi-history-911505', 'site': 'Crunchyroll'}, {'title': 'Episode 8 - Every Last Ninja on the Surface Will Be Annihilated', 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire3-tmb/9e092e76aa02ced73d6ead31f34aff811700707635_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-8-every-last-ninja-on-the-surface-will-be-annihilated-911504', 'site': 'Crunchyroll'}, {'title': 'Episode 7 - Meow Meow, Meow Meow, Meow Meow Meow Meow Meow?', 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire1-tmb/2b7b344e7b0e18bf42e5c84074a5ca1c1700130371_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-7-meow-meow-meow-meow-meow-meow-meow-meow-meow-911503', 'site': 'Crunchyroll'}, {'title': 'Episode 6 - The Lid on This Hellish Cauldron Has Come Off', 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire3-tmb/6731e206cce13ff4e3e51424f6886fe51699550735_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-6-the-lid-on-this-hellish-cauldron-has-come-off-911502', 'site': 'Crunchyroll'}, {'title': 'Episode 5 - Kumogakure Is Within the Top 10 Common Family Names in Japan (Lying)', 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire1-tmb/fa8ca1e7b36e373fcbd66300e21c2be81698941461_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-5-kumogakure-is-within-the-top-10-common-family-names-in-japan-lying-911501', 'site': 'Crunchyroll'}, {'title': 'Episode 4 - Do You Know What the Ninja Code Says?', 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire1-tmb/c5fa7560c8788d1dff76d39fe40f13171698336171_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-4-do-you-know-what-the-ninja-code-says-911500', 'site': 'Crunchyroll'}, {'title': 'Episode 3 - Boobs: So Close, Yet So Far', 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire1-tmb/45fff22cbc390bf0f014fae094c06bc91697731868_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-3-boobs-so-close-yet-so-far-911499', 'site': 'Crunchyroll'}, {'title': 'Episode 2 - I Want to Be a Ninja', 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire3-tmb/1351f659f860ea796b21433e342a228f1697131098_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-2-i-want-to-be-a-ninja-911498', 'site': 'Crunchyroll'}, {'title': 'Episode 1 - Throw a Rock, Hit a Ninja', 'thumbnail': 'https://img1.ak.crunchyroll.com/i/spire4-tmb/54a642ef12105133607491d176a9e7771696524475_full.jpg', 'url': 'http://www.crunchyroll.com/under-ninja/episode-1-throw-a-rock-hit-a-ninja-911497', 'site': 'Crunchyroll'}], 'externalLinks': [{'url': 'https://twitter.com/underninjaanime', 'site': 'Twitter', 'language': 'Japanese'}, {'url': 'https://under-ninja.jp/', 'site': 'Official Site', 'language': 'Japanese'}, {'url': 'https://www.crunchyroll.com/series/GQWH0M1WK/under-ninja', 'site': 'Crunchyroll', 'language': None}, {'url': 'https://www.iq.com/album/13zaq099nk9', 'site': 'iQ', 'language': None}], 'characters': {'nodes': [{'id': 255626, 'name': {'first': 'Kurou', 'last': 'Kumogakure'}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b255626-LUubIp17UYM3.png', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b255626-LUubIp17UYM3.png'}, 'description': None, 'gender': 'Male', 'age': None, 'siteUrl': 'https://anilist.co/character/255626'}, {'id': 305368, 'name': {'first': 'Katou', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b305368-uRfBnL1kb3RP.png', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b305368-uRfBnL1kb3RP.png'}, 'description': None, 'gender': 'Male', 'age': None, 'siteUrl': 'https://anilist.co/character/305368'}, {'id': 305369, 'name': {'first': 'Miracle', 'last': 'Hibi'}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b305369-XzM8VcG0dKlP.jpg', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b305369-XzM8VcG0dKlP.jpg'}, 'description': None, 'gender': 'Male', 'age': None, 'siteUrl': 'https://anilist.co/character/305369'}, {'id': 305371, 'name': {'first': 'Shion', 'last': 'Hachiya'}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b305371-Kyh8XIRbV1LN.jpg', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b305371-Kyh8XIRbV1LN.jpg'}, 'description': None, 'gender': None, 'age': None, 'siteUrl': 'https://anilist.co/character/305371'}, {'id': 305370, 'name': {'first': 'Suzuki', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b305370-KbRwucRKOanz.jpg', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b305370-KbRwucRKOanz.jpg'}, 'description': None, 'gender': None, 'age': None, 'siteUrl': 'https://anilist.co/character/305370'}, {'id': 310914, 'name': {'first': 'Kawado', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b310914-kV58Mz5AOXPd.jpg', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b310914-kV58Mz5AOXPd.jpg'}, 'description': None, 'gender': 'Female', 'age': None, 'siteUrl': 'https://anilist.co/character/310914'}, {'id': 310913, 'name': {'first': 'Eita', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b310913-6vgRlwklaiLt.jpg', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b310913-6vgRlwklaiLt.jpg'}, 'description': None, 'gender': 'Male', 'age': None, 'siteUrl': 'https://anilist.co/character/310913'}, {'id': 310915, 'name': {'first': 'Oono', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b310915-FSEtEtBYG49j.jpg', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b310915-FSEtEtBYG49j.jpg'}, 'description': None, 'gender': 'Male', 'age': None, 'siteUrl': 'https://anilist.co/character/310915'}, {'id': 310922, 'name': {'first': 'Noguchi', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b310922-CQyJmsBXcZgI.jpg', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b310922-CQyJmsBXcZgI.jpg'}, 'description': None, 'gender': 'Female', 'age': None, 'siteUrl': 'https://anilist.co/character/310922'}, {'id': 316589, 'name': {'first': 'Ozu', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b316589-A9iUITKQfOBG.png', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b316589-A9iUITKQfOBG.png'}, 'description': None, 'gender': 'Male', 'age': None, 'siteUrl': 'https://anilist.co/character/316589'}, {'id': 316969, 'name': {'first': 'Junna', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b316969-OyPq9SyvR6uz.png', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b316969-OyPq9SyvR6uz.png'}, 'description': None, 'gender': 'Female', 'age': '10', 'siteUrl': 'https://anilist.co/character/316969'}, {'id': 317166, 'name': {'first': 'Mako', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b317166-KDcRELR0mdBb.png', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b317166-KDcRELR0mdBb.png'}, 'description': None, 'gender': 'Female', 'age': None, 'siteUrl': 'https://anilist.co/character/317166'}, {'id': 317681, 'name': {'first': 'Sasama', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b317681-Wked1LlUktqr.png', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b317681-Wked1LlUktqr.png'}, 'description': '~!**Gender:** Female!~', 'gender': None, 'age': None, 'siteUrl': 'https://anilist.co/character/317681'}, {'id': 317682, 'name': {'first': 'Alexei', 'last': None}, 'image': {'large': 'https://s4.anilist.co/file/anilistcdn/character/large/b317682-USgEiZ6EGugV.png', 'medium': 'https://s4.anilist.co/file/anilistcdn/character/medium/b317682-USgEiZ6EGugV.png'}, 'description': None, 'gender': 'Male', 'age': None, 'siteUrl': 'https://anilist.co/character/317682'}]}}}}`

</details>

**Comment by ccubed** [comment]
Hi. I realized that I had left these off of the query for Anime. In addition, while I had idMal for manga I did not include popularity. I standardized the returns to now include idMal and popularity on both anime.get.anilist.show and manga.get.anilist.manga. Just update with pip and you should get 2.1.2. Thanks!
