### ISSUE TITLE
The xml used with parse_anime_data has no average score

### ISSUE THREAD

**Issue by lethargilistic** [ccubed/PyMoe#6]
# The problem
```python
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Pymoe import Mal
>>> instance = Mal('lethargilistic', 'notmyrealpassword :^)')
>>> user_lookup = instance.user('lethargilistic')
>>> [x.scores.average for x in user_lookup.anime.list]
[None, None, None, None, None, None, None, None, None, None, None, ... , None]
```

Every score is None, rather than the actual average score.

# The explanation
This issue refers to the xml retrieved by [this call in `Mal/__init__.py`](https://github.com/ccubed/PyMoe/blob/master/Pymoe/Mal/__init__.py#L278).

There is no value for the average score in that xml, so when it's parsed in [`parse_anime_data`](https://github.com/ccubed/PyMoe/blob/master/Pymoe/Mal/__init__.py#L305) and turned into an `Anime` object, the value for `Anime.scores.average` is always None.

Since it's the result of an API call, I see two options here:

1. Make another call to get the average score for *each* anime. (=_=)
1. Document that this doesn't work somewhere.

# The available xml fields
For clarity, here is a printout of the available data:
```
(Pdb) alias ll u;;d;;l
(Pdb) ll
> /.../Pymoe/Mal/__init__.py(285)user()
> /.../Pymoe/Mal/__init__.py(311)parse_anime_data()
(Pdb) for child in item.getchildren(): print('{tag:20} {child}'.format(tag=child.tag, child=child.text))
series_animedb_id    1
series_title         Cowboy Bebop
series_synonyms      COWBOY BEBOP; Cowboy Bebop
series_type          1
series_episodes      26
series_status        2
series_start         1998-04-03
series_end           1999-04-24
series_image         https://myanimelist.cdn-dena.com/images/anime/4/19644.jpg
my_id                0
my_watched_episodes  26
my_start_date        0000-00-00
my_finish_date       0000-00-00
my_score             10
my_status            2
my_rewatching        0
my_rewatching_ep     0
my_last_updated      1466632365
my_tags              None

```

**Comment by ccubed** [comment]
The average score isn't returned in the user endpoint. Do you think there's a better way to handle?

As for docs: http://pymoe.readthedocs.io/en/latest/malencap.html#NT_SCORES

**Comment by lethargilistic** [comment]
> As for docs: http://pymoe.readthedocs.io/en/latest/malencap.html#NT_SCORES

I am clearly blind. xD I think I was just confused by `user` also returning None before you merged  #5.

I don't think there's a better way to handle it from a code perspective.

However, that documentation might be improved by explicitly mentioning that the user endpoint _does_ return the `animeid`, which can in turn be used for looking up the average score, if desired.

**Comment by ccubed** [comment]
So probably move the documentation into the User endpoint area instead of the abstractions area. Seems like a good idea.

**Comment by ccubed** [comment]
Uploaded new documentation.
